INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (1,'et arcu','Brunei','Phasellus dapibus',1,1, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (2,'nec luctus','Canada','tincidunt adipiscing. Mauris molestie',2,2, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (3,'Suspendisse dui. Fusce','Montenegro','dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus',4,3, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (4,'Nam consequat','Hong Kong','magna. Sed eu eros. Nam consequat dolor vitae dolor.',5,4, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (5,'In lorem.','Sint Maarten','urna convallis erat, eget tincidunt dui',6,5, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (6,'libero. Morbi accumsan','Denmark','Curae; Donec tincidunt. Donec vitae erat',7,1, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (7,'sed consequat auctor,','Monaco','mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam',8,2, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (8,'dui, in','Cyprus','semper',9,3, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (9,'in sodales','Jersey','metus urna convallis erat, eget',10,4, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (10,'facilisis, magna','French Polynesia','nec, malesuada ut, sem. Nulla interdum. Curabitur dictum.',11,5, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (11,'euismod urna.','Papua New Guinea','ac mi eleifend egestas. Sed pharetra, felis',12,1, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (12,'dui lectus','Estonia','tristique',13,2, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (13,'elementum purus, accumsan','Grenada','lectus',14,3, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (14,'Donec','Montenegro','purus sapien, gravida non, sollicitudin a,',15,4, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (15,'cursus non, egestas','Jamaica','In',16,5, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (16,'dictum cursus. Nunc','Anguilla','pede. Praesent',17,1, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (17,'a,','Tokelau','nunc. In at pede. Cras',18,2, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (18,'Quisque imperdiet, erat','Western Sahara','elit. Nulla facilisi. Sed neque. Sed',19,3, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (19,'blandit enim','Marshall Islands','Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas',20,4, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId,publisherId, image_url, description) VALUES (20,'non nisi. Aenean','Lebanon','enim. Nunc',21,5, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (21,'ac,','Niue','dictum eleifend, nunc risus varius orci, in',22, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (22,'ornare, elit','Gabon','Cras sed leo. Cras vehicula aliquet',23, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (23,'Fusce','Pakistan','taciti sociosqu ad litora torquent per',24, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (24,'dolor dapibus gravida.','Suriname','mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam.',25, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (25,'vestibulum, neque sed','Mayotte','gravida nunc sed pede. Cum sociis',26, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (26,'dictum sapien. Aenean','Iran','lacus, varius et, euismod et, commodo at,',27, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (27,'habitant morbi tristique','Monaco','ut mi. Duis',1, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (28,'vel, mauris. Integer','Sri Lanka','dui. Cras pellentesque. Sed',2, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (29,'accumsan laoreet','Poland','ipsum leo elementum sem, vitae aliquam',3, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (30,'amet ornare lectus','Haiti','sodales purus, in',4, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (31,'massa. Quisque porttitor','Bangladesh','ullamcorper viverra. Maecenas',5, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (32,'gravida. Praesent','Ecuador','tellus. Nunc lectus',6, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (33,'Curabitur ut odio','Namibia','urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum',7, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (34,'magna.','Denmark','luctus, ipsum leo elementum',8, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (35,'placerat.','Curaçao','Aliquam tincidunt, nunc ac mattis ornare,',9, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (36,'sodales elit','Tanzania','eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer',10, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (37,'pede ac urna.','Rwanda','ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra',11, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (38,'Nullam scelerisque','Spain','turpis non enim. Mauris quis turpis vitae purus gravida sagittis.',12, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (39,'et ultrices','Slovakia','arcu. Vestibulum ut eros non enim',13, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (40,'et magnis dis','Sierra Leone','faucibus leo, in lobortis tellus justo sit amet',14, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (41,'eu','Haiti','odio a purus. Duis elementum, dui quis accumsan convallis,',15, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (42,'nulla vulputate dui,','Macao','sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum',16, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (43,'sollicitudin orci','Congo (Brazzaville)','imperdiet non, vestibulum nec, euismod',17, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (44,'Nullam vitae','Montserrat','congue a, aliquet',18, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (45,'dolor.','Italy','ac arcu. Nunc mauris. Morbi non sapien molestie orci',19, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (46,'id sapien.','Singapore','Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula',20, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (47,'placerat,','United States','ante.',21, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (48,'Suspendisse commodo tincidunt','Nauru','eu odio tristique pharetra. Quisque ac libero',22, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (49,'volutpat','Equatorial Guinea','sagittis felis. Donec tempor, est ac mattis',23, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (50,'mollis nec, cursus','Afghanistan','ullamcorper, velit in',24, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (51,'sodales purus,','Afghanistan','nibh. Phasellus nulla.',25, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (52,'mi. Aliquam','Azerbaijan','convallis',26, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (53,'aliquet vel, vulputate','Kuwait','eu erat semper rutrum. Fusce',27, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (54,'pulvinar','Western Sahara','pharetra nibh. Aliquam ornare, libero',1, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (55,'Fusce','United Kingdom (Great Britain)','interdum. Curabitur dictum. Phasellus in felis.',2, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (56,'tellus. Phasellus','Somalia','volutpat. Nulla dignissim. Maecenas',3, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (57,'Suspendisse','Uruguay','neque.',4, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (58,'mollis','Pakistan','ut nisi a odio semper cursus.',5, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (59,'nec, cursus','Palestine, State of','lacinia orci, consectetuer euismod est arcu ac',6, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (60,'arcu.','Jersey','ultrices a, auctor',7, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (61,'congue, elit sed','Syria','dui. Fusce diam nunc,',8, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (62,'tempus risus. Donec','Curaçao','eu nibh vulputate mauris sagittis placerat. Cras dictum',9, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (63,'non leo. Vivamus','Cocos (Keeling) Islands','tortor. Nunc',10, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (64,'a purus.','Brazil','massa. Suspendisse eleifend.',11, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (65,'magna','Micronesia','enim mi tempor lorem, eget mollis',12, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (66,'velit eget','Maldives','vel nisl. Quisque fringilla euismod enim.',13, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (67,'dui. Fusce','Zambia','egestas. Sed pharetra, felis eget',14, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (68,'tempor erat','Bermuda','Proin',15, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (69,'libero lacus,','Bahrain','neque non quam. Pellentesque habitant morbi tristique senectus et',16, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (70,'in','Laos','Mauris ut quam vel sapien',17, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (71,'Mauris magna. Duis','Afghanistan','mus. Donec dignissim',18, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (72,'mauris blandit','Norway','egestas hendrerit neque. In ornare sagittis felis. Donec',19, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (73,'semper et, lacinia','Holy See (Vatican City State)','Integer aliquam adipiscing lacus. Ut',20, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (74,'nisi. Mauris nulla.','Bouvet Island','vel lectus. Cum sociis natoque penatibus et',21, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (75,'Donec','Bolivia','ac nulla. In tincidunt congue turpis. In condimentum. Donec',22, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (76,'dolor. Donec','New Zealand','rutrum urna, nec luctus felis purus ac',23, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (77,'arcu vel quam','Belarus','sociis natoque penatibus et magnis dis',24, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (78,'morbi','Paraguay','ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas',25, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (79,'consequat purus. Maecenas','Austria','at, iaculis quis, pede. Praesent eu',26, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (80,'quis,','Mayotte','vitae, aliquet nec, imperdiet nec,',27, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (81,'Duis dignissim tempor','Saudi Arabia','amet, dapibus id,',1, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (82,'sagittis.','Bahamas','bibendum sed, est. Nunc laoreet lectus quis',2, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (83,'nec, imperdiet','Zimbabwe','Mauris vestibulum, neque',3, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (84,'ac','Slovenia','eu, placerat eget, venenatis a, magna. Lorem ipsum',4, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (85,'Sed eu','Tajikistan','justo sit amet nulla. Donec non justo. Proin',5, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (86,'sem elit,','United Kingdom (Great Britain)','adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.',6, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (87,'Quisque','Bolivia','facilisis facilisis, magna tellus',7, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (88,'velit egestas lacinia.','Liechtenstein','magna. Duis dignissim tempor arcu. Vestibulum ut',8, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (89,'nonummy ac, feugiat','Belarus','Nulla eu neque pellentesque massa lobortis ultrices. Vivamus',9, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (90,'vitae, aliquet nec,','Korea, North','Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec,',10, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (91,'commodo tincidunt','Sao Tome and Principe','interdum feugiat. Sed nec metus facilisis lorem tristique',11, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (92,'augue, eu tempor','Saint Lucia','augue. Sed molestie. Sed id risus quis diam luctus lobortis.',12, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (93,'ut cursus luctus,','Liechtenstein','Maecenas',13, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (94,'dui augue','Moldova','feugiat nec, diam. Duis mi enim,',14, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (95,'lacus.','Nigeria','Aliquam ultrices',15, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (96,'vel, vulputate eu,','Israel','dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero.',16, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (97,'auctor velit.','Comoros','hendrerit a, arcu. Sed et libero. Proin mi. Aliquam',17, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (98,'aliquet lobortis,','Comoros','at fringilla purus mauris a nunc. In',18, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (99,'arcu.','Paraguay','ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper',19, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
INSERT INTO "Books" (id,Title,Country,Keywords,catagoryId, image_url, description) VALUES (100,'volutpat nunc sit','Zambia','ac turpis egestas. Aliquam fringilla cursus purus. Nullam',20, "https://firstfreerockford.org/wp-content/uploads/2018/08/placeholder-book-cover-default.png", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");


-- Pass=`echo -n john | sha256sum`
-- | username | Pass | selfInfo |
INSERT INTO "Users" VALUES
(
	'john',
	'96d9632f363564cc3032521409cf22a852f2032eec099ed5967c0d000cec607a',
	'hi, my name is john'
);

INSERT INTO "Users" VALUES
(
	'smith',
	'6627835f988e2c5e50533d491163072d3f4f41f5c8b04630150debb3722ca2dd',
	'hi, my name is smith'
);

INSERT INTO "Users" VALUES
(
	'jack',
	'31611159e7e6ff7843ea4627745e89225fc866621cfcfdbd40871af4413747cc',
	'hi, my name is jack'
);

-- | id | name | owner |
INSERT INTO "Collections" VALUES(1, 'main', 'john');
INSERT INTO "Collections" VALUES(2, 'second', 'john');
INSERT INTO "Collections" VALUES(3, 'third', 'john');
INSERT INTO "Collections" VALUES(4, 'main', 'smith');

-- | collections_id | book_id |
INSERT INTO "Collections__Book" VALUES(1, 1 , date('1999-01-01'));
INSERT INTO "Collections__Book" VALUES(1, 2 , date('1999-01-09'));
INSERT INTO "Collections__Book" VALUES(1, 3 , date('1999-01-08'));
INSERT INTO "Collections__Book" VALUES(1, 4 , date('1999-01-04'));
INSERT INTO "Collections__Book" VALUES(2, 20, date('1999-01-05'));
INSERT INTO "Collections__Book" VALUES(3, 30, date('1999-01-06'));
INSERT INTO "Collections__Book" VALUES(4, 40, date('1999-01-07'));

-- | id | review | rating | reviewer | book |
INSERT INTO "Reviews" VALUES (1, "Not bad",     3, "john",  1);
INSERT INTO "Reviews" VALUES (2, "Good",        4, "john",  2);
INSERT INTO "Reviews" VALUES (3, "Trash",       0, "smith", 2);
INSERT INTO "Reviews" VALUES (4, "my review",   4, "smith", 2);
INSERT INTO "Reviews" VALUES (5, "your review", 5, "smith", 3);

-- Print all tables
-- SELECT name FROM sqlite_master WHERE type='table'

-- All possible catagorys
-- | id | catagory |
INSERT INTO "Catagorys" VALUES (1, "Arts and Music");
INSERT INTO "Catagorys" VALUES (2, "Biographies");
INSERT INTO "Catagorys" VALUES (3, "Business");
INSERT INTO "Catagorys" VALUES (4, "Comics");
INSERT INTO "Catagorys" VALUES (5, "Computers and Tech");
INSERT INTO "Catagorys" VALUES (6, "Cooking");
INSERT INTO "Catagorys" VALUES (7, "Entertainment");
INSERT INTO "Catagorys" VALUES (8, "Health and Fitness");
INSERT INTO "Catagorys" VALUES (9, "History");
INSERT INTO "Catagorys" VALUES (10, "Hobbies and Crafts");
INSERT INTO "Catagorys" VALUES (11, "Home and Garden");
INSERT INTO "Catagorys" VALUES (12, "Horror");
INSERT INTO "Catagorys" VALUES (13, "Kids");
INSERT INTO "Catagorys" VALUES (14, "Literature and Fiction");
INSERT INTO "Catagorys" VALUES (15, "Medical");
INSERT INTO "Catagorys" VALUES (16, "Mysteries");
INSERT INTO "Catagorys" VALUES (17, "Parenting");
INSERT INTO "Catagorys" VALUES (18, "Romance");
INSERT INTO "Catagorys" VALUES (19, "Sci-Fi and Fantasy");
INSERT INTO "Catagorys" VALUES (20, "Science and Math");
INSERT INTO "Catagorys" VALUES (21, "Self-Help");
INSERT INTO "Catagorys" VALUES (22, "Social Sciences");
INSERT INTO "Catagorys" VALUES (23, "Sports");
INSERT INTO "Catagorys" VALUES (24, "Teen");
INSERT INTO "Catagorys" VALUES (25, "Travel");
INSERT INTO "Catagorys" VALUES (26, "True Crime");
INSERT INTO "Catagorys" VALUES (27, "Westerns");

-- | id | publisher |
INSERT INTO "Publishers" VALUES (1, "TCK Publishing");
INSERT INTO "Publishers" VALUES (2, "Reed Elsevier");
INSERT INTO "Publishers" VALUES (3, "Penguin Random House");
INSERT INTO "Publishers" VALUES (4, "Harper Collins");
INSERT INTO "Publishers" VALUES (5, "Simon & Schuster");
INSERT INTO "Publishers" VALUES (6, "Pan Macmillan");
INSERT INTO "Publishers" VALUES (7, "Bloomsbury");

-- | id | name |
INSERT INTO "Authors" VALUES (1, "Gallo");
INSERT INTO "Authors" VALUES (2, "Sive");
INSERT INTO "Authors" VALUES (3, "Milly");
INSERT INTO "Authors" VALUES (4, "Kristy");
INSERT INTO "Authors" VALUES (5, "Chet");
INSERT INTO "Authors" VALUES (6, "Malcom");
INSERT INTO "Authors" VALUES (7, "Alex");
INSERT INTO "Authors" VALUES (8, "Bob");

-- | authorId | bookId |
INSERT INTO "Authors_Books" VALUES (1, 1);
INSERT INTO "Authors_Books" VALUES (1, 2);
INSERT INTO "Authors_Books" VALUES (2, 1);
INSERT INTO "Authors_Books" VALUES (2, 2);
INSERT INTO "Authors_Books" VALUES (2, 3);
INSERT INTO "Authors_Books" VALUES (2, 4);
INSERT INTO "Authors_Books" VALUES (3, 1);
INSERT INTO "Authors_Books" VALUES (4, 3);
INSERT INTO "Authors_Books" VALUES (5, 3);
INSERT INTO "Authors_Books" VALUES (5, 4);
INSERT INTO "Authors_Books" VALUES (5, 5);
INSERT INTO "Authors_Books" VALUES (5, 6);
INSERT INTO "Authors_Books" VALUES (6, 5);
INSERT INTO "Authors_Books" VALUES (6, 6);
INSERT INTO "Authors_Books" VALUES (7, 6);
INSERT INTO "Authors_Books" VALUES (8, 1);
